### ISSUE TITLE
Error when attempting to update skill tree assets

### ISSUE THREAD

**Issue by cwinkramboll** [EmmittJ/PoESkillTree#240]
Exception: System.IO.IOException: The process cannot access the file 'skill_sprite-active-3-09487b78c46e37b8f28de82f7d812cc4.jpg' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at POESKillTree.Views.MainWindow.Menu_RedownloadTreeAssets(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 541
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MLanghof** [comment]
Does this happen every time? Can you check for the mentioned file? Can you delete it manually? Maybe your antivirus was coincidentally accessing the file at the time?

**Comment by cwinkramboll** [comment]
The error happens repeatedly and i cannot locate the named file. I believe it's due to a firewall blocking the programs access, see this second error message I received:

The error time: 04/01/2016 16:11
Exception: System.IO.IOException: The process cannot access the file 'skill_sprite-active-3-09487b78c46e37b8f28de82f7d812cc4.jpg' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at POESKillTree.Views.MainWindow.Menu_RedownloadTreeAssets(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 541
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
The error time: 04/01/2016 16:13
Exception: System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x88982F50
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at POESKillTree.SkillTreeFiles.ImageHelper.OnLoadBitmapImage(Uri uri) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\ImageHelper.cs:line 14
   at POESKillTree.SkillTreeFiles.SkillIcons.OpenOrDownloadImages(UpdateLoadingWindow update) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillIcons.cs:line 35
   at POESKillTree.SkillTreeFiles.SkillTree..ctor(String treestring, Boolean displayProgress, UpdateLoadingWindow update) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 305
   at POESKillTree.SkillTreeFiles.SkillTree.CreateSkillTree(StartLoadingWindow start, UpdateLoadingWindow update, CloseLoadingWindow finish) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 629
   at POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 209
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
Exception: System.Runtime.InteropServices.COMException (0x88982F50): Exception from HRESULT: 0x88982F50
The error time: 04/01/2016 16:13
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at POESKillTree.Views.MainWindow.GetLevelAsString() in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 751
   at POESKillTree.Views.MainWindow.Window_Closing(Object sender, CancelEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 321
   at System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
The error time: 05/01/2016 17:19
Exception: System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x88982F50
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at POESKillTree.SkillTreeFiles.ImageHelper.OnLoadBitmapImage(Uri uri) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\ImageHelper.cs:line 14
   at POESKillTree.SkillTreeFiles.SkillIcons.OpenOrDownloadImages(UpdateLoadingWindow update) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillIcons.cs:line 35
   at POESKillTree.SkillTreeFiles.SkillTree..ctor(String treestring, Boolean displayProgress, UpdateLoadingWindow update) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 305
   at POESKillTree.SkillTreeFiles.SkillTree.CreateSkillTree(StartLoadingWindow start, UpdateLoadingWindow update, CloseLoadingWindow finish) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 629
   at POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 209
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
Exception: System.Runtime.InteropServices.COMException (0x88982F50): Exception from HRESULT: 0x88982F50
The error time: 05/01/2016 17:19
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at POESKillTree.Views.MainWindow.GetLevelAsString() in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 751
   at POESKillTree.Views.MainWindow.Window_Closing(Object sender, CancelEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 321
   at System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by cwinkramboll** [comment]
I can successfully use release 2.2.3 as I do not have to update any assets.

**Comment by l0g0sys** [comment]
If you use some 3rd party (non-Microsoft) anti-virus/malware software, 
try to add exception for PoESkillTree.exe process/executable to not get 
scanned by real-time protection scanner. It might be finding something 
suspicious in file/filename and then moving it to quarantine.
