### ISSUE TITLE
Application crashed and then would not boot up (even after reinstall)

### ISSUE THREAD

**Issue by PatrickGriffiths** [EmmittJ/PoESkillTree#330]
I was using the application, the system it was on was running Windows7 64bit. I clicked to compare a build with one I was making and suddenly it crashed on me, then presented me with this message upon trying to boot it up: [http://i.imgur.com/0CCXUkR.png](url)

I removed the software with a complete wipe of the data from my machine, reinstalled the latest version, I got the same error message, I have tried shutting and down and rebooting and I have looked through the processes active and 'nothing' that I can see is using the process. 

Below is the debug.txt log... 

> The error time: 01/06/2016 21:28
Exception: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderItemDB.Read15_ItemDB()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at POESKillTree.SkillTreeFiles.ItemDB.Load(String file, Boolean index) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\ItemDB.cs:line 1385
   at POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 378
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception: System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderItemDB.Read15_ItemDB()

I'm not sure what exactly caused the initial crash, I've never had that happen before with a simple comparison of my builds, but this is a really weird issue, not sure what to do to fix it if a clean install did nothing... Any help is appreciated.

Kind Regards,
Patrick Griffiths.

**Comment by EmmittJ** [comment]
https://github.com/EmmittJ/PoESkillTree/wiki/How-To:-Copy-Builds

Delete the file mentioned here. That should fix the problem.

**Comment by PatrickGriffiths** [comment]
I did actually try to delete this file and run it, I had no luck at all though. I'll try the portable version and get back to you.

**Comment by PatrickGriffiths** [comment]
I completely removed everything again and retried the portable version, its working fine right now. (:))
