### ISSUE TITLE
crashing when opening

### ISSUE THREAD

**Issue by Khons204** [EmmittJ/PoESkillTree#334]
hey crashing when opening tried reinstalling and deleteing appdata and restarting pc everytime get error and this is in the debug file

The error time: 6/6/2016 8:53 AM
Exception: System.IO.IOException: The process cannot access the file 'C:\Users\Paul\AppData\Roaming\PoESkillTree - Ascendancy\Items.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at POESKillTree.SkillTreeFiles.ItemDB.Load(String file, Boolean index) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\ItemDB.cs:line 1384
   at POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 378
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by l0g0sys** [comment]
Did you install it with .exe installer or used .zip package?

**Comment by EmmittJ** [comment]
You also may want to restart your computer and try again.

**Comment by l0g0sys** [comment]
Or maybe some aggressive antivirus/malware software is acting?

**Comment by Khons204** [comment]
i did try restarting my computer twice already and i used the .exe to install but this actually  happened on 2.2.09 initially i think it crashed when i was planning a tree if i remeber correctly

**Comment by brather1ng** [comment]
This is most likely out of our control as that file from the log is accessed exactly once. It is probably some kind of antivirus scanner.

**Comment by brather1ng** [comment]
I have just accidentally reproduced this while testing something entirely different.

If you download the latest zip release (no need to actually use that) and copy the Items.xml file from the zip into the folder specified in you debug log above, this crash should go away. If it still crashes, it should be something different as this crash was probably caused by you deleting the AppData folder.

If you still crash, please post your full debug.txt

**Comment by Khons204** [comment]
this worked thanks brather1ng

**Comment by brather1ng** [comment]
Nice!
