### ISSUE TITLE
Crash on "Download & Import Items"  Unknown weapon type: Stiletto

### ISSUE THREAD

**Issue by randomsvensson** [EmmittJ/PoESkillTree#373]
Crashes when I copy paste item data from:
https://www.pathofexile.com/character-window/get-items?character=CHARACTER&accountName=ACCOUNT
Same error on restart until "<ItemData />" in PersistentData.xml is reset.  backup works
debug.txt
> `
Exception: System.Exception: Unknown weapon type: Stiletto
   at POESKillTree.SkillTreeFiles.Compute.Weapon..ctor(WeaponHand hand, Item item) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\SkillTreeFiles\Compute.cs:line 1514
   at POESKillTree.SkillTreeFiles.Compute.Initialize(SkillTree skillTree, ItemAttributes itemAttrs) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\SkillTreeFiles\Compute.cs:line 2307
   at POESKillTree.Views.MainWindow.UpdateStatistics() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 1216
   at POESKillTree.Views.MainWindow.UpdateUI() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 1102
   at POESKillTree.Views.MainWindow.<LoadItemData>d__132.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 1624
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at POESKillTree.Views.MainWindow.<SetCurrentBuild>d__148.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 1805
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at POESKillTree.Views.MainWindow.<Window_Loaded>d__66.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 474
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`<

**Comment by brather1ng** [comment]
That should go away when you redownload `ItemList.xml` (you can find a new one [here](https://raw.githubusercontent.com/EmmittJ/PoESkillTree/master/WPFSKillTree/Data/Equipment/ItemList.xml)) located in `Data/Equipment/` in the same folder as your `PersistentData.xml` ([How To: Copy Builds](https://github.com/EmmittJ/PoESkillTree/wiki/How-To:-Copy-Builds) explains how to find it).

Now the question is, how does that file get corrupted ...
Please attach your current `ItemList.xml` file here before replacing it so we can try to find the bug.

**Comment by randomsvensson** [comment]
ItemList.xml
http://puu.sh/rcFVM/422efe0737.xml

I replaced it with the new one but same error.
Thanks for the work you put into this tool, keep it up. :+1:

**Comment by Azualend** [comment]
When I downloaded and imported my equipment the program crashed and gave me the following error message:

The program crashed. A stack trace can be found at: C:...\AppData\Roaming\PoESkillTree - Atlas of Worlds\debug.txt

However, that location does not exist. I have tried to uninstall and then reinstall many times and I get the same message.

**Comment by EmmittJ** [comment]
%appdata%\PoESkillTree - Atlas of Worlds\debug.txt

On Sep 15, 2016 11:25 PM, "Azualend" <notifications@github.com> wrote:

When I downloaded and imported my equipment the program crashed and gave me
the following error message:

The program crashed. A stack trace can be found at:
C:...\AppData\Roaming\PoESkillTree
- Atlas of Worlds\debug.txt

However, that location does not exist. I have tried to uninstall and then
reinstall many times and I get the same message.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EmmittJ/PoESkillTree/issues/373#issuecomment-247527373>,
or mute the thread

**Comment by brather1ng** [comment]
Both of you probably need to remove the `PersiststenData.xml` file (see [How To: Copy Builds](https://github.com/EmmittJ/PoESkillTree/wiki/How-To:-Copy-Builds) for its location).

If that does solve the issue, please attach the old problematic one.

**Comment by randomsvensson** [comment]
Tried and it did not help the error but I can use everything but the `Download & Import Items` function.
`debug.txt` and  `PersiststenData.xml`
http://puu.sh/rdlrS/647359a892.zip

I have portable edition if that helps any.

**Comment by brather1ng** [comment]
Thanks!

Weird, your `PersistentData.xml` loads fine for me (both on the latest release and the development version).

If you open the crafting window ("Equipment" tab, "Craft new item"), does it list all base items ("Stiletto" in particular)? If yes, if you craft a weapon, can you equip it without crashing?

**Comment by randomsvensson** [comment]
Did not work but I updated to 2.4.0pre from 2.3.0 and now its working. 
Thanks for the awesome program and for the assistance.
