### ISSUE TITLE
Crashes on import passive tree link

### ISSUE THREAD

**Issue by d07RiV** [EmmittJ/PoESkillTree#387]
If I go to my character profile and copy the passive link, it contains query parameters with my character and account name. The tool doesn't seem to like that and crashes.

Example link: https://www.pathofexile.com/passive-skill-tree/AAAABAIDAABeAO4D7gguDXwOSA5cD8QRLxFQEZYVIBXXGY4dqh2-IvQo-ioLKjgqTSsKLL8s6S9vM4c1uTdMO3w9Xz8nQZZEDUV-RnFJsUrITLNRTFJTVIJWY1fJWW1d8l9qX5hfsGSdavpsC20Zb55wUnC7fVt_gH-Wf8aCx4MJhG-ExYauhrOJ04w2jZKP-pMnl5WX9JuNm7WfbaEvoqOj76crrEeus7QMtUi4yrmTvorBxcMJwzrHncjwykrK088y0B_Q0ND1037UQtfP2RPhiOq662Pr9ewY7YPveu-I7-vyHfaj9z35N_5J_xA=?accountName=Rivx&characterName=Rivpf

The error time: 10/3/2016 11:54 PM

```
Exception: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at POESKillTree.SkillTreeFiles.SkillTree.DecodeUrl(String url, HashSet`1& skillednodes, Int32& chartype, Int32& asctype) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\SkillTreeFiles\SkillTree.cs:line 1156
   at POESKillTree.SkillTreeFiles.SkillTree.LoadFromUrl(String url) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\SkillTreeFiles\SkillTree.cs:line 1197
   at POESKillTree.Views.MainWindow.<CurrentBuildOnPropertyChanged>d__65.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 225
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by EmmittJ** [comment]
Same issue as #386. It will be fixed in the next release :)
