### ISSUE TITLE
getting an error that will not let me open poeskilltree

### ISSUE THREAD

**Issue by yoxgit** [EmmittJ/PoESkillTree#424]
here is the message im getting from debug text file

Exception: POESKillTree.TreeGenerator.Model.PseudoAttributes.PseudoAttributeDataInvalidException: No Pseudo Attributes loaded. Make sure C:\Users\yoxgi\AppData\Roaming\PoESkillTree - Atlas of Worlds\Data\PseudoAttributes is not empty.  ((never erased anything here, yet the folder is empty))
   at POESKillTree.TreeGenerator.Model.PseudoAttributes.PseudoAttributeLoader.LoadPseudoAttributes(XmlPseudoAttributes xmlPseudoAttributes)
   at POESKillTree.TreeGenerator.ViewModels.AdvancedTabViewModel.ReloadPseudoAttributes()
   at POESKillTree.TreeGenerator.ViewModels.AdvancedTabViewModel..ctor(SkillTree tree, IDialogCoordinator dialogCoordinator, Object dialogContext, Action`1 runCallback)
   at POESKillTree.TreeGenerator.ViewModels.SettingsViewModel..ctor(SkillTree tree, ISettingsDialogCoordinator dialogCoordinator)
   at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction.<set_SkillTree>b__16_0()
   at POESKillTree.Utils.Notifier.SetProperty[T](T& backingStore, T value, Action onChanged, Action`1 onChanging, String propertyName)
   at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction.set_SkillTree(SkillTree value)
   at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction..ctor(ISettingsDialogCoordinator dialogCoordinator, IPersistentData persistentData, SkillTree skillTree)
   at POESKillTree.Views.MainWindow.<Window_Loaded>d__81.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by brather1ng** [comment]
Duplicate, see #398.

You can manually copy the files from the portable release (https://github.com/EmmittJ/PoESkillTree/releases/download/2.5.0/PoESkillTree-AtlasofWorlds-2.5.0.zip) to that directory and it should work again.

This seems to be a regular problem. However, I have no idea why the installer sometimes skips these files.
