### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Markadamsjr** [EmmittJ/PoESkillTree#454]
So I started up my offline planner and got this message.https://gyazo.com/d725c92c5129a930f79edb4a2ab33b47
when i go there it says this.

The error time: 11/19/2016 10:31 AM
Exception: System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at POESKillTree.SkillTreeFiles.Updater.IsNewerProductInstalled() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\SkillTreeFiles\Updater.cs:line 439
   at POESKillTree.SkillTreeFiles.Updater.CheckForUpdates(Boolean Prerelease) in C:\GitHub\PoESkillTree_Source\WPFSkillTree\SkillTreeFiles\Updater.cs:line 245
   at POESKillTree.Views.MainWindow.<>c.<Menu_CheckForUpdates>b__98_0() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 935
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at POESKillTree.Views.MainWindow.<AwaitAsyncTask>d__169`1.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at POESKillTree.Views.MainWindow.<Menu_CheckForUpdates>d__98.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSkillTree\Views\MainWindow.xaml.cs:line 933
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Markadamsjr** [comment]
I have tried re installing it

**Comment by MLanghof** [comment]
> The error time: 11/19/2016 10:31 AM

...uh, that's weird.

**Comment by EmmittJ** [comment]
Is there anything else in the file? That crash time is 5 months old.
