### ISSUE TITLE
[2.7] PseudoAttributeDataInvalidException Crash on Launch

### ISSUE THREAD

**Issue by Retik** [EmmittJ/PoESkillTree#472]
I installed and then deleted the %appdata%\PoESkillTree - The fall of Oriath and now when I launch I'm getting this exception.

The error time: 6/7/2017 5:05 PM
Exception: POESKillTree.TreeGenerator.Model.PseudoAttributes.PseudoAttributeDataInvalidException: No Pseudo Attributes loaded. Make sure C:\Users\Ian\AppData\Roaming\PoESkillTree - The Fall of Oriath\Data\PseudoAttributes is not empty.
   at POESKillTree.TreeGenerator.Model.PseudoAttributes.PseudoAttributeLoader.LoadPseudoAttributes(XmlPseudoAttributes xmlPseudoAttributes) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\Model\PseudoAttributes\PseudoAttributeLoader.cs:line 74
   at POESKillTree.TreeGenerator.ViewModels.AdvancedTabViewModel.ReloadPseudoAttributes() in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\AdvancedTabViewModel.cs:line 657
   at POESKillTree.TreeGenerator.ViewModels.AdvancedTabViewModel..ctor(SkillTree tree, IDialogCoordinator dialogCoordinator, Object dialogContext, Action`1 runCallback) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\AdvancedTabViewModel.cs:line 601
   at POESKillTree.TreeGenerator.ViewModels.SettingsViewModel..ctor(SkillTree tree, ISettingsDialogCoordinator dialogCoordinator, Object dialogContext) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\SettingsViewModel.cs:line 56
   at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction.<set_SkillTree>b__16_0() in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\TreeGeneratorInteraction.cs:line 36
   at POESKillTree.Utils.Notifier.SetProperty[T](T& backingStore, T value, Action onChanged, Action`1 onChanging, String propertyName) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\Utils\Notifier.cs:line 37
   at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction.set_SkillTree(SkillTree value) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\TreeGeneratorInteraction.cs:line 33
   at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction..ctor(ISettingsDialogCoordinator dialogCoordinator, IPersistentData persistentData, SkillTree skillTree) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\TreeGeneratorInteraction.cs:line 49
   at POESKillTree.Views.MainWindow.<Window_Loaded>d__90.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 570
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
The error time: 6/7/2017 5:05 PM
Exception: POESKillTree.TreeGenerator.Model.PseudoAttributes.PseudoAttributeDataInvalidException: No Pseudo Attributes loaded. Make sure C:\Users\Ian\AppData\Roaming\PoESkillTree - The Fall of Oriath\Data\PseudoAttributes is not empty.
   at POESKillTree.TreeGenerator.Model.PseudoAttributes.PseudoAttributeLoader.LoadPseudoAttributes(XmlPseudoAttributes xmlPseudoAttributes) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\Model\PseudoAttributes\PseudoAttributeLoader.cs:line 74
   at POESKillTree.TreeGenerator.ViewModels.AdvancedTabViewModel.ReloadPseudoAttributes() in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\AdvancedTabViewModel.cs:line 657
   at POESKillTree.TreeGenerator.ViewModels.AdvancedTabViewModel..ctor(SkillTree tree, IDialogCoordinator dialogCoordinator, Object dialogContext, Action`1 runCallback) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\AdvancedTabViewModel.cs:line 601
   at POESKillTree.TreeGenerator.ViewModels.SettingsViewModel..ctor(SkillTree tree, ISettingsDialogCoordinator dialogCoordinator, Object dialogContext) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\SettingsViewModel.cs:line 56
   at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction.<set_SkillTree>b__16_0() in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\TreeGeneratorInteraction.cs:line 36
   at POESKillTree.Utils.Notifier.SetProperty[T](T& backingStore, T value, Action onChanged, Action`1 onChanging, String propertyName) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\Utils\Notifier.cs:line 37
   at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction.set_SkillTree(SkillTree value) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\TreeGeneratorInteraction.cs:line 33
   at POESKillTree.TreeGenerator.ViewModels.TreeGeneratorInteraction..ctor(ISettingsDialogCoordinator dialogCoordinator, IPersistentData persistentData, SkillTree skillTree) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\TreeGenerator\ViewModels\TreeGeneratorInteraction.cs:line 49
   at POESKillTree.Views.MainWindow.<Window_Loaded>d__90.MoveNext() in C:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 570
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by EmmittJ** [comment]
https://github.com/EmmittJ/PoESkillTree/wiki/Program-crash:-"No-Pseudo-Attributes-loaded."
